# @package _global_

type: sfm
work_dir: ${hydra:runtime.cwd}
redo: True
hololens: True

# scan_data_dir: ${work_dir}/data/onepose_datasets/val_data
scan_data_dir: ${work_dir}/data/costum_datasets/test

dataset:
    max_num_kp3d: 2500
    max_num_kp2d: 1000

    data_dir:
        # - ${scan_data_dir}/0606-tiger-others tiger-2
        - ${scan_data_dir}/demo_capture demo-1

    outputs_dir: ${work_dir}/data/sfm_model/{}


network:
    detection: superpoint
    detection_model_path: ${work_dir}/data/models/extractors/SuperPoint/superpoint_v1.pth

    matching: superglue
    matching_model_path: ${work_dir}/data/models/matchers/SuperGlue/superglue_outdoor.pth

sfm:
    down_ratio: 5
    covis_num: 10
    rotation_thresh: 50

disable_lightning_logs: True
